openapi: 3.0.3
info:
  title: Full Stack Scaffolding API - Serverless
  description: Serverless API with FastAPI, Neon PostgreSQL, and Clerk authentication
  version: 1.0.0
servers:
  - url: https://api.example.com
    description: Production server (Vercel)
  - url: http://localhost:3000
    description: Development server
paths:
  /api/hello-world:
    get:
      summary: Get hello world message
      description: Returns a personalized hello world message for authenticated users and logs the access
      operationId: getHelloWorld
      security:
        - ClerkAuth: []
      responses:
        '200':
          description: Successful response with hello world message and request count
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HelloWorldResponse'
        '401':
          description: Unauthorized - missing or invalid token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error or database connection failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /api/health:
    get:
      summary: Health check endpoint
      description: Returns service health status and database connectivity (no authentication required)
      operationId: getHealth
      responses:
        '200':
          description: Service is healthy and database is accessible
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'
        '503':
          description: Service unhealthy or database connection failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'
  /api/user/settings:
    get:
      summary: Get user settings
      description: Returns the current user's settings and preferences
      operationId: getUserSettings
      security:
        - ClerkAuth: []
      responses:
        '200':
          description: User settings retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserSettings'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      summary: Update user settings
      description: Updates the current user's settings
      operationId: updateUserSettings
      security:
        - ClerkAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserSettingsInput'
      responses:
        '200':
          description: Settings updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserSettings'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  securitySchemes:
    ClerkAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Clerk authentication token (JWT)

  schemas:
    HelloWorldResponse:
      type: object
      required:
        - message
        - userId
        - timestamp
        - status
      properties:
        message:
          type: string
          description: The hello world message
          enum: ["hello world"]
        userId:
          type: string
          description: The authenticated user's ID from Clerk
        timestamp:
          type: string
          description: ISO 8601 timestamp of the response
          format: date-time
        status:
          type: string
          description: Response status
          enum: ["success"]
        requestCount:
          type: integer
          description: Number of times user accessed hello world endpoint
          minimum: 0

    UserSettings:
      type: object
      required:
        - userId
        - theme
        - notificationsEnabled
        - createdAt
        - updatedAt
      properties:
        userId:
          type: string
          description: Clerk user ID
        theme:
          type: string
          description: UI theme preference
          enum: ["light", "dark", "system"]
          default: "light"
        notificationsEnabled:
          type: boolean
          description: Whether notifications are enabled
          default: true
        createdAt:
          type: string
          format: date-time
          description: When settings were created
        updatedAt:
          type: string
          format: date-time
          description: When settings were last updated

    UserSettingsInput:
      type: object
      properties:
        theme:
          type: string
          enum: ["light", "dark", "system"]
        notificationsEnabled:
          type: boolean

    HealthResponse:
      type: object
      required:
        - status
        - timestamp
        - version
        - database
      properties:
        status:
          type: string
          description: Health status
          enum: ["ok", "error"]
        timestamp:
          type: string
          description: ISO 8601 timestamp of the health check
          format: date-time
        version:
          type: string
          description: API version
        database:
          type: string
          description: Database connectivity status
          enum: ["connected", "disconnected"]

    Error:
      type: object
      required:
        - error
        - message
        - timestamp
      properties:
        error:
          type: string
          description: Error type
        message:
          type: string
          description: Detailed error message
        timestamp:
          type: string
          description: ISO 8601 timestamp of the error
          format: date-time

security:
  - ClerkAuth: []
